feat(Room) added inserting to db data from placeholderApi
NikitaSkubak-core/TestForMyJob pull request #4
Opened 2020-11-27 11:54 UTC by meansWorker

добавил room в проект, посмотри еще PostRepository, я там добавил метод convertListOFPlaceHolderPostToListOfPost для конвертирования списка с одного типа в другой (для записи в бд), в принципе его функционал я бы смог повторить в юз кейсе, где использовал (чекни PostUseCase), я так могу делать (добавить такой метод в репозиторий) или все таки делать нужно такое в юз кейсе? или это все равноправное(такая мелкая задачка)?

2020-11-27 12:29 UTC, meansWorker commented
Вопрос снят, в машине подумал и решил что в юз кейсе просто конвертирование сделаю

2020-11-27 15:42 UTC, meansWorker commented
добавил javadoc`и и почистил код

2020-11-30 08:27 UTC, IvanKnyaziev requested changes
1. Имена таблиц не  должны быть с маленькой буквы
2. С БД нельза работать как с Observable
fun insertComments(comments: List<Comment>): Observable<List<Long>>
точнее можно но это  не тот случай

2020-11-30 09:05 UTC, meansWorker commented
разработку проекта окончил

2020-11-30 14:38 UTC, IvanKnyaziev approved these changes

2020-11-30 14:38 UTC, merged